// Auto-generate spriteManifest.js from frontend/public/sprites/
const fs = require('fs');
const path = require('path');

const SPRITES_DIR = path.join(__dirname, '..', 'public', 'sprites');

const CATEGORY_CONFIG = {
  tiles:     { name: 'Tiles',     tileW: 16, tileH: 16 },
  crops:     { name: 'Crops',     tileW: 16, tileH: 16 },
  buildings: { name: 'Buildings', tileW: 16, tileH: 16 },
  decor:     { name: 'Decor',     tileW: 16, tileH: 16 },
  fence:     { name: 'Fence',     tileW: 16, tileH: 16 },
  trees:     { name: 'Trees',     tileW: 16, tileH: 16 },
  animals:   { name: 'Animals',   tileW: 16, tileH: 16 },
  enemies:   { name: 'Enemies',   tileW: 16, tileH: 16 },
  npcs:      { name: 'NPCs',      tileW: 16, tileH: 16 },
  icons:     { name: 'Icons',     tileW: 16, tileH: 16 },
  player:    { name: 'Player',    tileW: 64, tileH: 64 },
  other:     { name: 'Other',     tileW: 16, tileH: 16 },
  weather:   { name: 'Weather',   tileW: 16, tileH: 16 },
};

const categories = [];

for (const [folder, config] of Object.entries(CATEGORY_CONFIG)) {
  const dir = path.join(SPRITES_DIR, folder);
  if (!fs.existsSync(dir)) continue;

  const files = fs.readdirSync(dir)
    .filter(f => f.endsWith('.png'))
    .sort();

  if (files.length === 0) continue;

  const sheets = files.map(f => {
    const label = f.replace('.png', '').replace(/_/g, ' ');
    const animated = /(_Anim|_Animation|_animation|_anim)\.png$/i.test(f);
    const entry = {
      path: `sprites/${folder}/${f}`,
      tileW: config.tileW,
      tileH: config.tileH,
      label,
    };
    if (animated) entry.animated = true;
    return entry;
  });

  categories.push({ name: config.name, sheets });
}

// Write the manifest
const output = `// Generated by scripts/generateSpriteManifest.js — do not edit manually
export const SPRITE_CATEGORIES = ${JSON.stringify(categories, null, 2)};
`;

const outPath = path.join(__dirname, '..', 'src', 'components', 'editor', 'spriteManifest.js');
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath}`);
console.log(`${categories.length} categories, ${categories.reduce((s, c) => s + c.sheets.length, 0)} sheets total`);
