// Auto-generate spriteManifest.js from frontend/public/sprites/ and frontend/public/animations/
const fs = require('fs');
const path = require('path');

const SPRITES_DIR = path.join(__dirname, '..', 'public', 'sprites');
const ANIMS_DIR = path.join(__dirname, '..', 'public', 'animations');

const CATEGORY_CONFIG = {
  tiles:     { name: 'Tiles',     tileW: 16, tileH: 16 },
  crops:     { name: 'Crops',     tileW: 16, tileH: 16 },
  buildings: { name: 'Buildings', tileW: 16, tileH: 16 },
  decor:     { name: 'Decor',     tileW: 16, tileH: 16 },
  fence:     { name: 'Fence',     tileW: 16, tileH: 16 },
  trees:     { name: 'Trees',     tileW: 16, tileH: 16 },
  animals:   { name: 'Animals',   tileW: 16, tileH: 16 },
  enemies:   { name: 'Enemies',   tileW: 16, tileH: 16 },
  npcs:      { name: 'NPCs',      tileW: 16, tileH: 16 },
  icons:     { name: 'Icons',     tileW: 16, tileH: 16 },
  player:    { name: 'Player',    tileW: 64, tileH: 64 },
  other:     { name: 'Other',     tileW: 16, tileH: 16 },
  weather:   { name: 'Weather',   tileW: 16, tileH: 16 },
};

const categories = [];

for (const [folder, config] of Object.entries(CATEGORY_CONFIG)) {
  const sheets = [];

  // Static sprites from sprites/{folder}/
  const spriteDir = path.join(SPRITES_DIR, folder);
  if (fs.existsSync(spriteDir)) {
    const files = fs.readdirSync(spriteDir)
      .filter(f => f.endsWith('.png'))
      .sort();
    for (const f of files) {
      sheets.push({
        path: `sprites/${folder}/${f}`,
        tileW: config.tileW,
        tileH: config.tileH,
        label: f.replace('.png', '').replace(/_/g, ' '),
      });
    }
  }

  // Animated sprites from animations/{folder}/
  const animDir = path.join(ANIMS_DIR, folder);
  if (fs.existsSync(animDir)) {
    const files = fs.readdirSync(animDir)
      .filter(f => f.endsWith('.png'))
      .sort();
    for (const f of files) {
      sheets.push({
        path: `animations/${folder}/${f}`,
        tileW: config.tileW,
        tileH: config.tileH,
        label: f.replace('.png', '').replace(/_/g, ' '),
        animated: true,
      });
    }
  }

  if (sheets.length > 0) {
    categories.push({ name: config.name, sheets });
  }
}

// Write the manifest
const output = `// Generated by scripts/generateSpriteManifest.js — do not edit manually
export const SPRITE_CATEGORIES = ${JSON.stringify(categories, null, 2)};
`;

const outPath = path.join(__dirname, '..', 'src', 'components', 'editor', 'spriteManifest.js');
fs.writeFileSync(outPath, output);
const totalSheets = categories.reduce((s, c) => s + c.sheets.length, 0);
const animSheets = categories.reduce((s, c) => s + c.sheets.filter(sh => sh.animated).length, 0);
console.log(`Wrote ${outPath}`);
console.log(`${categories.length} categories, ${totalSheets} sheets total (${totalSheets - animSheets} static, ${animSheets} animated)`);
