// Generated by scripts/generateSpriteManifest.js — do not edit manually
export const SPRITE_CATEGORIES = [
  {
    "name": "Tiles",
    "sheets": [
      {
        "path": "sprites/tiles/Beach_Beach_Decor_Tiles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Beach Beach Decor Tiles"
      },
      {
        "path": "sprites/tiles/Beach_Beach_Tiles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Beach Beach Tiles"
      },
      {
        "path": "sprites/tiles/Bridge_Bridge_Stone_Horizontal.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bridge Bridge Stone Horizontal"
      },
      {
        "path": "sprites/tiles/Bridge_Bridge_Stone_Vertical.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bridge Bridge Stone Vertical"
      },
      {
        "path": "sprites/tiles/Bridge_Bridge_Wood.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bridge Bridge Wood"
      },
      {
        "path": "sprites/tiles/Bridge_Bridge_Wood_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bridge Bridge Wood 1"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Doorway_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Doorway 1"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Floor_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Floor 1"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Floor_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Floor 2"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Floor_Decoration.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Floor Decoration"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Floor_Ladder.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Floor Ladder"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Floor_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Floor Middle"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Support_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Support 1"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Support_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Support 2"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Wall_Support.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Wall Support"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Walls.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Walls"
      },
      {
        "path": "sprites/tiles/Cave_Cave_Water.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Water"
      },
      {
        "path": "sprites/tiles/Cave_Rails.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Rails"
      },
      {
        "path": "sprites/tiles/Cliff_Cave_Entrance.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Cave Entrance"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_1_Cave_Entrance.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 1 Cave Entrance"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_1_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 1 Tile"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_2_Cave_Entrance.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 2 Cave Entrance"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_2_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 2 Tile"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_3_Cave_Entrance.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 3 Cave Entrance"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_3_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 3 Tile"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_4_Cave_Entrance.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 4 Cave Entrance"
      },
      {
        "path": "sprites/tiles/Cliff_Stone_Cliff_4_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cliff Stone Cliff 4 Tile"
      },
      {
        "path": "sprites/tiles/Cobble_Road_Cobble_Road_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cobble Road Cobble Road 1"
      },
      {
        "path": "sprites/tiles/Cobble_Road_Cobble_Road_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cobble Road Cobble Road 2"
      },
      {
        "path": "sprites/tiles/FarmLand_FarmLand_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "FarmLand FarmLand Tile"
      },
      {
        "path": "sprites/tiles/FarmLand_FarmLand_Wet_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "FarmLand FarmLand Wet Tile"
      },
      {
        "path": "sprites/tiles/FarmLand_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "FarmLand Tile"
      },
      {
        "path": "sprites/tiles/Grass_1_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass 1 Middle"
      },
      {
        "path": "sprites/tiles/Grass_Grass_1_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass 1 Middle"
      },
      {
        "path": "sprites/tiles/Grass_Grass_2_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass 2 Middle"
      },
      {
        "path": "sprites/tiles/Grass_Grass_3_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass 3 Middle"
      },
      {
        "path": "sprites/tiles/Grass_Grass_4_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass 4 Middle"
      },
      {
        "path": "sprites/tiles/Grass_Grass_Tiles_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass Tiles 1"
      },
      {
        "path": "sprites/tiles/Grass_Grass_Tiles_1_Blob_TEST.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass Tiles 1 Blob TEST"
      },
      {
        "path": "sprites/tiles/Grass_Grass_Tiles_1_Blob_TEST_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass Tiles 1 Blob TEST 1"
      },
      {
        "path": "sprites/tiles/Grass_Grass_Tiles_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass Tiles 2"
      },
      {
        "path": "sprites/tiles/Grass_Grass_Tiles_3.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass Tiles 3"
      },
      {
        "path": "sprites/tiles/Grass_Grass_Tiles_4.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Grass Tiles 4"
      },
      {
        "path": "sprites/tiles/Grass_Path_Decoration.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Path Decoration"
      },
      {
        "path": "sprites/tiles/Grass_Path_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Path Middle"
      },
      {
        "path": "sprites/tiles/Grass_Tiles_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grass Tiles 1"
      },
      {
        "path": "sprites/tiles/Hedge_Tiles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Hedge Tiles"
      },
      {
        "path": "sprites/tiles/Path_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Path Middle"
      },
      {
        "path": "sprites/tiles/Pavement_Tiles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pavement Tiles"
      },
      {
        "path": "sprites/tiles/Picnic_Blankets.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Picnic Blankets"
      },
      {
        "path": "sprites/tiles/Water_Decoration.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Decoration"
      },
      {
        "path": "sprites/tiles/Water_Fish_Animated_Tile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Fish Animated Tile"
      },
      {
        "path": "sprites/tiles/Water_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Middle"
      },
      {
        "path": "sprites/tiles/Water_Tile_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Tile 1"
      },
      {
        "path": "sprites/tiles/Water_Water_Decoration.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Decoration"
      },
      {
        "path": "sprites/tiles/Water_Water_Middle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Middle"
      },
      {
        "path": "sprites/tiles/Water_Water_Middle_Anim_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Middle Anim 1"
      },
      {
        "path": "sprites/tiles/Water_Water_Middle_Anim_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Middle Anim 2"
      },
      {
        "path": "sprites/tiles/Water_Water_Stone_Tile_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 1"
      },
      {
        "path": "sprites/tiles/Water_Water_Stone_Tile_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 2"
      },
      {
        "path": "sprites/tiles/Water_Water_Stone_Tile_3.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 3"
      },
      {
        "path": "sprites/tiles/Water_Water_Stone_Tile_4.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 4"
      },
      {
        "path": "sprites/tiles/Water_Water_Tile_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 1"
      },
      {
        "path": "sprites/tiles/Water_Water_Tile_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 2"
      },
      {
        "path": "sprites/tiles/Water_Water_Tile_3.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 3"
      },
      {
        "path": "sprites/tiles/Water_Water_Tile_4.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 4"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_1.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 1"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 2"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_3.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 3"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_4.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 4"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_5.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 5"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_6.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 6"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_7.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 7"
      },
      {
        "path": "sprites/tiles/Waterfall_Waterfall_8.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Waterfall Waterfall 8"
      },
      {
        "path": "sprites/tiles/Wooden_Deck_Tiles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Wooden Deck Tiles"
      },
      {
        "path": "animations/tiles/Cave_Cave_Water_Animation.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Cave Water Animation",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Foam_Animation.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Foam Animation",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Stone_Tile_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 1 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Stone_Tile_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 2 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Stone_Tile_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 3 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Stone_Tile_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Stone Tile 4 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Tile_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 1 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Tile_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 2 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Tile_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 3 Anim",
        "animated": true
      },
      {
        "path": "animations/tiles/Water_Water_Tile_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Water Water Tile 4 Anim",
        "animated": true
      }
    ]
  },
  {
    "name": "Crops",
    "sheets": [
      {
        "path": "sprites/crops/Apple_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Apple Tree"
      },
      {
        "path": "sprites/crops/Berries.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Berries"
      },
      {
        "path": "sprites/crops/Cherry_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cherry Tree"
      },
      {
        "path": "sprites/crops/Crops.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Crops"
      },
      {
        "path": "sprites/crops/Crops_2.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Crops 2"
      },
      {
        "path": "sprites/crops/Fruit_Tree_Stages.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fruit Tree Stages"
      },
      {
        "path": "sprites/crops/Fruit_Trees_Fruit_Objects.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fruit Trees Fruit Objects"
      },
      {
        "path": "sprites/crops/Grapes_Bower.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Grapes Bower"
      },
      {
        "path": "sprites/crops/Peach_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Peach Tree"
      },
      {
        "path": "sprites/crops/Pear_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pear Tree"
      }
    ]
  },
  {
    "name": "Buildings",
    "sheets": [
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_1_Limestone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 1 Limestone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_1_Limestone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 1 Limestone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_1_Limestone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 1 Limestone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_2_Limestone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 2 Limestone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_2_Limestone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 2 Limestone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_2_Limestone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 2 Limestone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_3_Limestone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 3 Limestone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_3_Limestone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 3 Limestone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_3_Limestone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 3 Limestone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_4_Limestone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 4 Limestone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_4_Limestone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 4 Limestone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_4_Limestone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 4 Limestone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_5_Limestone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 5 Limestone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_5_Limestone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 5 Limestone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Limestone_House_5_Limestone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Limestone House 5 Limestone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_1_Stone_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 1 Stone Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Base_Blackpng.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Base Blackpng"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_2_Stone_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 2 Stone Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_3_Stone_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 3 Stone Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_4_Stone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 4 Stone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_4_Stone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 4 Stone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_4_Stone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 4 Stone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Stone_House_5_Stone_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Stone House 5 Stone Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_1_Wood_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 1 Wood Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_2_Wood_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 2 Wood Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_3_Wood_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 3 Wood Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_4_Wood_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 4 Wood Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Red Black"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Red_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Red Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Houses_Wood_House_5_Wood_Red_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Houses Wood House 5 Wood Red Red"
      },
      {
        "path": "sprites/buildings/Buildings_Tent_Tent_Big.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Tent Tent Big"
      },
      {
        "path": "sprites/buildings/Buildings_Tent_Tent_Interior.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Tent Tent Interior"
      },
      {
        "path": "sprites/buildings/Buildings_Tent_Tent_Small.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Tent Tent Small"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Base_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Base Black"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Base_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Base Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Base_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Base Red"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Green_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Green Black"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Green_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Green Blue"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Green_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Green Red"
      },
      {
        "path": "sprites/buildings/Buildings_Unique_Buildings_Barn_Barn_Red_Black.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Buildings Unique Buildings Barn Barn Red Black"
      }
    ]
  },
  {
    "name": "Decor",
    "sheets": [
      {
        "path": "sprites/decor/Benches.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Benches"
      },
      {
        "path": "sprites/decor/Boat.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Boat"
      },
      {
        "path": "sprites/decor/Camp_Decor.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Camp Decor"
      },
      {
        "path": "sprites/decor/Cave_Decorations.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cave Decorations"
      },
      {
        "path": "sprites/decor/Fence_Big.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fence Big"
      },
      {
        "path": "sprites/decor/Fences.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fences"
      },
      {
        "path": "sprites/decor/Flowers.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Flowers"
      },
      {
        "path": "sprites/decor/Fountain.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fountain"
      },
      {
        "path": "sprites/decor/Hay_Bales.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Hay Bales"
      },
      {
        "path": "sprites/decor/Lanter_Posts.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Lanter Posts"
      },
      {
        "path": "sprites/decor/Lantern.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Lantern"
      },
      {
        "path": "sprites/decor/Minecrats.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Minecrats"
      },
      {
        "path": "sprites/decor/Nests.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Nests"
      },
      {
        "path": "sprites/decor/Ores.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Ores"
      },
      {
        "path": "sprites/decor/Outdoor_Decor.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor"
      },
      {
        "path": "sprites/decor/Outdoor_Decor_Animations_Other_Animations_Fence_Big_Gate.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Fence Big Gate"
      },
      {
        "path": "sprites/decor/Outdoor_Decor_Animations_Other_Animations_Fence_Big_Gate_Vertical.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Fence Big Gate Vertical"
      },
      {
        "path": "sprites/decor/Scarecrows.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Scarecrows"
      },
      {
        "path": "sprites/decor/barrels.png",
        "tileW": 16,
        "tileH": 16,
        "label": "barrels"
      },
      {
        "path": "animations/decor/Big_Torch_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Big Torch Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Flower_Grass_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Flower Grass 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Flower_Grass_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Flower Grass 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Flower_Grass_6_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Flower Grass 6 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Flower_Grass_8_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Flower Grass 8 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Lillypad_Green_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Lillypad Green 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Lillypad_Purple_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Lillypad Purple 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Break_Animations_Barrel_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Break Animations Barrel 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Break_Animations_Crate_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Break Animations Crate Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Break_Animations_Sign_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Break Animations Sign 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Break_Animations_Sign_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Break Animations Sign 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Not_Potted_Flowers_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Not Potted Flowers 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Not_Potted_Flowers_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Not Potted Flowers 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Not_Potted_Flowers_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Not Potted Flowers 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Not_Potted_Flowers_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Not Potted Flowers 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Not_Potted_Flowers_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Not Potted Flowers 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Potted_Flowers_1_Potted_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Potted Flowers 1 Potted Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Potted_Flowers_2_Potted_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Potted Flowers 2 Potted Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Potted_Flowers_3_Potted_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Potted Flowers 3 Potted Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Potted_Flowers_4_Potted_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Potted Flowers 4 Potted Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Flower_Animations_Potted_Flowers_5_Potted_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Flower Animations Potted Flowers 5 Potted Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_10_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 10 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_11_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 11 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_12_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 12 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_13_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 13 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_14_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 14 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_15_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 15 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_6_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 6 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_7_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 7 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_8_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 8 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Flower_Grass_9_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Flower Grass 9 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Grass_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Grass 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Grass_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Grass 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Grass_Animations_Grass_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Grass Animations Grass 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_6_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 6 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_7_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 7 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Muschroom_Animations_muschroom_8_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Muschroom Animations muschroom 8 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Boat_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Boat Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Campfire_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Campfire Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Fountain_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Fountain Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Pole_and_Bunting_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Pole and Bunting 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Pole_and_Bunting_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Pole and Bunting 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Torch_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Torch Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Other_Animations_Torch_small_anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Other Animations Torch small anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Cave_Rock_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Cave Rock 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Cave_Rock_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Cave Rock 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Cave_Rock_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Cave Rock 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Cave_Rock_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Cave Rock 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_10_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 10 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_11_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 11 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_12_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 12 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_13_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 13 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_14_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 14 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_6_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 6 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_7_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 7 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_8_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 8 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Rock_Animations_Rock_9_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Rock Animations Rock 9 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Other_Water_Decor_Branch_Water_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Other Water Decor Branch Water Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Other_Water_Decor_Log_1_Water_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Other Water Decor Log 1 Water Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Other_Water_Decor_Log_2_Water_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Other Water Decor Log 2 Water Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Other_Water_Decor_Log_3_Water_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Other Water Decor Log 3 Water Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Cattail_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Cattail 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Cattail_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Cattail 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Cattail_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Cattail 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Cattail_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Cattail 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Cattail_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Cattail 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Brown_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Brown 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Brown_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Brown 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Brown_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Brown 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Brown_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Brown 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Brown_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Brown 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Brown_6_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Brown 6 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Green_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Green 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Green_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Green 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Green_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Green 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Green_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Green 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Green_5_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Green 5 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Green_6_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Green 6 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Purple_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Purple 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Purple_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Purple 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Purple_3_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Purple 3 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Outdoor_Decor_Animations_Water_Decor_Animations_Water_Plants_Lillypad_Purple_4_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outdoor Decor Animations Water Decor Animations Water Plants Lillypad Purple 4 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Rock_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Rock 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/Rock_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Rock 2 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/muschroom_1_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "muschroom 1 Anim",
        "animated": true
      },
      {
        "path": "animations/decor/muschroom_2_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "muschroom 2 Anim",
        "animated": true
      }
    ]
  },
  {
    "name": "Fence",
    "sheets": [
      {
        "path": "sprites/fence/Fence_Big.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fence Big"
      },
      {
        "path": "sprites/fence/Fences.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fences"
      },
      {
        "path": "sprites/fence/White_Fence.png",
        "tileW": 16,
        "tileH": 16,
        "label": "White Fence"
      }
    ]
  },
  {
    "name": "Trees",
    "sheets": [
      {
        "path": "sprites/trees/Big_Birch_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Big Birch Tree"
      },
      {
        "path": "sprites/trees/Big_Fruit_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Big Fruit Tree"
      },
      {
        "path": "sprites/trees/Big_Oak_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Big Oak Tree"
      },
      {
        "path": "sprites/trees/Big_Spruce_tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Big Spruce tree"
      },
      {
        "path": "sprites/trees/Birch_Leaf_Particle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Birch Leaf Particle"
      },
      {
        "path": "sprites/trees/Medium_Birch_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Medium Birch Tree"
      },
      {
        "path": "sprites/trees/Medium_Fruit_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Medium Fruit Tree"
      },
      {
        "path": "sprites/trees/Medium_Oak_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Medium Oak Tree"
      },
      {
        "path": "sprites/trees/Medium_Spruce_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Medium Spruce Tree"
      },
      {
        "path": "sprites/trees/Oak_Leaf_Particle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Oak Leaf Particle"
      },
      {
        "path": "sprites/trees/Small_Birch_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Small Birch Tree"
      },
      {
        "path": "sprites/trees/Small_Fruit_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Small Fruit Tree"
      },
      {
        "path": "sprites/trees/Small_Oak_Tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Small Oak Tree"
      },
      {
        "path": "sprites/trees/Small_Spruce_tree.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Small Spruce tree"
      },
      {
        "path": "sprites/trees/Spruce_Needle_Particle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Spruce Needle Particle"
      }
    ]
  },
  {
    "name": "Animals",
    "sheets": [
      {
        "path": "sprites/animals/Albino_Kapybara_Bubbles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Albino Kapybara Bubbles"
      },
      {
        "path": "sprites/animals/Albino_Kapybara_Dive.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Albino Kapybara Dive"
      },
      {
        "path": "sprites/animals/Albino_Kapybara_Emerge.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Albino Kapybara Emerge"
      },
      {
        "path": "sprites/animals/Albino_Kapybara_Idle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Albino Kapybara Idle"
      },
      {
        "path": "sprites/animals/Albino_Kapybara_LookAround.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Albino Kapybara LookAround"
      },
      {
        "path": "sprites/animals/Albino_Kapybara_LookAround_submerged.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Albino Kapybara LookAround submerged"
      },
      {
        "path": "sprites/animals/Bee_Hive.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bee Hive"
      },
      {
        "path": "sprites/animals/Bee_Nest.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bee Nest"
      },
      {
        "path": "sprites/animals/Butterfly.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Butterfly"
      },
      {
        "path": "sprites/animals/Chicken_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 01"
      },
      {
        "path": "sprites/animals/Chicken_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 02"
      },
      {
        "path": "sprites/animals/Chicken_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 03"
      },
      {
        "path": "sprites/animals/Chicken_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 04"
      },
      {
        "path": "sprites/animals/Chicken_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 05"
      },
      {
        "path": "sprites/animals/Chicken_06.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 06"
      },
      {
        "path": "sprites/animals/Chicken_07.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 07"
      },
      {
        "path": "sprites/animals/Chicken_08.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 08"
      },
      {
        "path": "sprites/animals/Chicken_09.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 09"
      },
      {
        "path": "sprites/animals/Chicken_10.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 10"
      },
      {
        "path": "sprites/animals/Chicken_11.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 11"
      },
      {
        "path": "sprites/animals/Chicken_12.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 12"
      },
      {
        "path": "sprites/animals/Chicken_13.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 13"
      },
      {
        "path": "sprites/animals/Chicken_14.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 14"
      },
      {
        "path": "sprites/animals/Chicken_15.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 15"
      },
      {
        "path": "sprites/animals/Chicken_16.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 16"
      },
      {
        "path": "sprites/animals/Chicken_17.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 17"
      },
      {
        "path": "sprites/animals/Chicken_18.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken 18"
      },
      {
        "path": "sprites/animals/Chicken_Rooster.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chicken Rooster"
      },
      {
        "path": "sprites/animals/Cow_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 01"
      },
      {
        "path": "sprites/animals/Cow_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 02"
      },
      {
        "path": "sprites/animals/Cow_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 03"
      },
      {
        "path": "sprites/animals/Cow_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 04"
      },
      {
        "path": "sprites/animals/Cow_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 05"
      },
      {
        "path": "sprites/animals/Cow_06.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 06"
      },
      {
        "path": "sprites/animals/Cow_07.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 07"
      },
      {
        "path": "sprites/animals/Cow_08.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 08"
      },
      {
        "path": "sprites/animals/Cow_09.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Cow 09"
      },
      {
        "path": "sprites/animals/Duck_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Duck 01"
      },
      {
        "path": "sprites/animals/Duck_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Duck 02"
      },
      {
        "path": "sprites/animals/Duck_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Duck 03"
      },
      {
        "path": "sprites/animals/Duck_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Duck 04"
      },
      {
        "path": "sprites/animals/Duck_in_a_hat.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Duck in a hat"
      },
      {
        "path": "sprites/animals/Frog_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Frog 01"
      },
      {
        "path": "sprites/animals/Frog_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Frog 02"
      },
      {
        "path": "sprites/animals/Frog_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Frog 03"
      },
      {
        "path": "sprites/animals/Frog_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Frog 04"
      },
      {
        "path": "sprites/animals/Frog_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Frog 05"
      },
      {
        "path": "sprites/animals/Frog_06.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Frog 06"
      },
      {
        "path": "sprites/animals/Goose_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Goose 01"
      },
      {
        "path": "sprites/animals/Goose_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Goose 02"
      },
      {
        "path": "sprites/animals/Goose_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Goose 03"
      },
      {
        "path": "sprites/animals/Goose_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Goose 04"
      },
      {
        "path": "sprites/animals/Goose_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Goose 05"
      },
      {
        "path": "sprites/animals/Goose_06.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Goose 06"
      },
      {
        "path": "sprites/animals/Horse_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Horse 01"
      },
      {
        "path": "sprites/animals/Horse_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Horse 02"
      },
      {
        "path": "sprites/animals/Horse_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Horse 03"
      },
      {
        "path": "sprites/animals/Horse_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Horse 04"
      },
      {
        "path": "sprites/animals/Horse_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Horse 05"
      },
      {
        "path": "sprites/animals/Kapybara_Bubbles.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Kapybara Bubbles"
      },
      {
        "path": "sprites/animals/Kapybara_Dive.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Kapybara Dive"
      },
      {
        "path": "sprites/animals/Kapybara_Emerge.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Kapybara Emerge"
      },
      {
        "path": "sprites/animals/Kapybara_Idle.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Kapybara Idle"
      },
      {
        "path": "sprites/animals/Kapybara_LookAround.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Kapybara LookAround"
      },
      {
        "path": "sprites/animals/Kapybara_LookAround_submerged.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Kapybara LookAround submerged"
      },
      {
        "path": "sprites/animals/Mouse_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Mouse 01"
      },
      {
        "path": "sprites/animals/Mouse_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Mouse 02"
      },
      {
        "path": "sprites/animals/Mouse_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Mouse 03"
      },
      {
        "path": "sprites/animals/Mouse_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Mouse 04"
      },
      {
        "path": "sprites/animals/Pig_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 01"
      },
      {
        "path": "sprites/animals/Pig_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 02"
      },
      {
        "path": "sprites/animals/Pig_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 03"
      },
      {
        "path": "sprites/animals/Pig_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 04"
      },
      {
        "path": "sprites/animals/Pig_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 05"
      },
      {
        "path": "sprites/animals/Pig_06.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 06"
      },
      {
        "path": "sprites/animals/Pig_07.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 07"
      },
      {
        "path": "sprites/animals/Pig_08.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 08"
      },
      {
        "path": "sprites/animals/Pig_09.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 09"
      },
      {
        "path": "sprites/animals/Pig_10.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 10"
      },
      {
        "path": "sprites/animals/Pig_11.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 11"
      },
      {
        "path": "sprites/animals/Pig_12.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 12"
      },
      {
        "path": "sprites/animals/Pig_13.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 13"
      },
      {
        "path": "sprites/animals/Pig_14.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 14"
      },
      {
        "path": "sprites/animals/Pig_15.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 15"
      },
      {
        "path": "sprites/animals/Pig_16.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Pig 16"
      },
      {
        "path": "sprites/animals/Rooster.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Rooster"
      },
      {
        "path": "sprites/animals/Sheep_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 01"
      },
      {
        "path": "sprites/animals/Sheep_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 02"
      },
      {
        "path": "sprites/animals/Sheep_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 03"
      },
      {
        "path": "sprites/animals/Sheep_04.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 04"
      },
      {
        "path": "sprites/animals/Sheep_05.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 05"
      },
      {
        "path": "sprites/animals/Sheep_06.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 06"
      },
      {
        "path": "sprites/animals/Sheep_07.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 07"
      },
      {
        "path": "sprites/animals/Sheep_08.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 08"
      },
      {
        "path": "sprites/animals/Sheep_09.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Sheep 09"
      },
      {
        "path": "sprites/animals/Swan_01.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Swan 01"
      },
      {
        "path": "sprites/animals/Swan_02.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Swan 02"
      },
      {
        "path": "sprites/animals/Swan_03.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Swan 03"
      },
      {
        "path": "animations/animals/Bee_Flying_Animation.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bee Flying Animation",
        "animated": true
      }
    ]
  },
  {
    "name": "Enemies",
    "sheets": [
      {
        "path": "animations/enemies/Bombschroom_Bombschroom.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bombschroom Bombschroom",
        "animated": true
      },
      {
        "path": "animations/enemies/Bombschroom_Toxic_Gas_Cloud_VFX.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bombschroom Toxic Gas Cloud VFX",
        "animated": true
      },
      {
        "path": "animations/enemies/Skeleton_Skeleton.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Skeleton",
        "animated": true
      },
      {
        "path": "animations/enemies/Skeleton_Skeleton_Bowman_Merged_Skeleton_Bowman.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Skeleton Bowman Merged Skeleton Bowman",
        "animated": true
      },
      {
        "path": "animations/enemies/Skeleton_Skeleton_Bowman_Separated_Skeleton_Bowman_Bow.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Skeleton Bowman Separated Skeleton Bowman Bow",
        "animated": true
      },
      {
        "path": "animations/enemies/Skeleton_Skeleton_Bowman_Separated_Skeleton_Bowman_Separated.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Skeleton Bowman Separated Skeleton Bowman Separated",
        "animated": true
      },
      {
        "path": "animations/enemies/Skeleton_Skeleton_Mage.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Skeleton Mage",
        "animated": true
      },
      {
        "path": "animations/enemies/Skeleton_Skeleton_Swordman.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Skeleton Swordman",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Big_Slime_Big_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Big Slime Big Blue",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Big_Slime_Big_Green.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Big Slime Big Green",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Big_Slime_Big_Pink.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Big Slime Big Pink",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Big_Slime_Big_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Big Slime Big Red",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Big_Slime_Big_Yellow.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Big Slime Big Yellow",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Medium_Slime_Medium_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Medium Slime Medium Blue",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Medium_Slime_Medium_Green.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Medium Slime Medium Green",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Medium_Slime_Medium_Pink.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Medium Slime Medium Pink",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Medium_Slime_Medium_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Medium Slime Medium Red",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Medium_Slime_Medium_Yellow.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Medium Slime Medium Yellow",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Small_Slime_Small_Blue.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Small Slime Small Blue",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Small_Slime_Small_Green.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Small Slime Small Green",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Small_Slime_Small_Pink.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Small Slime Small Pink",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Small_Slime_Small_Red.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Small Slime Small Red",
        "animated": true
      },
      {
        "path": "animations/enemies/Slime_Slime_Small_Slime_Small_Yellow.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Slime Slime Small Slime Small Yellow",
        "animated": true
      }
    ]
  },
  {
    "name": "NPCs",
    "sheets": [
      {
        "path": "sprites/npcs/Bartender_Bruno.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bartender Bruno"
      },
      {
        "path": "sprites/npcs/Bartender_Katy.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bartender Katy"
      },
      {
        "path": "sprites/npcs/Chef_Chloe.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Chef Chloe"
      },
      {
        "path": "sprites/npcs/Farmer_Bob.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Farmer Bob"
      },
      {
        "path": "sprites/npcs/Farmer_Buba.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Farmer Buba"
      },
      {
        "path": "sprites/npcs/Fisherman_Fin.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Fisherman Fin"
      },
      {
        "path": "sprites/npcs/Lumberjack_Jack.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Lumberjack Jack"
      },
      {
        "path": "sprites/npcs/Miner_Mike.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Miner Mike"
      }
    ]
  },
  {
    "name": "Icons",
    "sheets": [
      {
        "path": "sprites/icons/No_Outline_Food_Icons_NO_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "No Outline Food Icons NO Outline"
      },
      {
        "path": "sprites/icons/No_Outline_Other_Icons_NO_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "No Outline Other Icons NO Outline"
      },
      {
        "path": "sprites/icons/No_Outline_Resources_Icons_NO_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "No Outline Resources Icons NO Outline"
      },
      {
        "path": "sprites/icons/No_Outline_Tool_Icons_NO_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "No Outline Tool Icons NO Outline"
      },
      {
        "path": "sprites/icons/Outline_Food_Icons_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outline Food Icons Outline"
      },
      {
        "path": "sprites/icons/Outline_Other_Icons_2_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outline Other Icons 2 Outline"
      },
      {
        "path": "sprites/icons/Outline_Other_Icons_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outline Other Icons Outline"
      },
      {
        "path": "sprites/icons/Outline_Resources_Icons_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outline Resources Icons Outline"
      },
      {
        "path": "sprites/icons/Outline_Tool_Icons_Outline.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Outline Tool Icons Outline"
      }
    ]
  },
  {
    "name": "Player",
    "sheets": [
      {
        "path": "sprites/player/Accessories_Farmer_Hat_1.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Accessories Farmer Hat 1"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Black.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Black"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Blue.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Blue"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Green.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Green"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Orange.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Orange"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Pink.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Pink"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Purple.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Purple"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_Red.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 Red"
      },
      {
        "path": "sprites/player/Chest_Farmer_Shirt_Farmer_Shirt_1_White_and_Brown.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Farmer Shirt Farmer Shirt 1 White and Brown"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Black.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Black"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Blue.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Blue"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Brown.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Brown"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Green.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Green"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Orange.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Orange"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Pink.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Pink"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Purple.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Purple"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_Red.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 Red"
      },
      {
        "path": "sprites/player/Chest_Lumberjack_Shirt_Lumberjack_Shirt_1_White.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest Lumberjack Shirt Lumberjack Shirt 1 White"
      },
      {
        "path": "sprites/player/Chest_OG_Shirt_Shirt_1_Black.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest OG Shirt Shirt 1 Black"
      },
      {
        "path": "sprites/player/Chest_OG_Shirt_Shirt_1_Blue.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest OG Shirt Shirt 1 Blue"
      },
      {
        "path": "sprites/player/Chest_OG_Shirt_Shirt_1_Brown.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest OG Shirt Shirt 1 Brown"
      },
      {
        "path": "sprites/player/Chest_OG_Shirt_Shirt_1_Green.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Chest OG Shirt Shirt 1 Green"
      },
      {
        "path": "sprites/player/Farmer_Pants_1_Blue.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Farmer Pants 1 Blue"
      },
      {
        "path": "sprites/player/Farmer_Shirt_1_Blue.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Farmer Shirt 1 Blue"
      },
      {
        "path": "sprites/player/Hair_1_Brown.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Hair 1 Brown"
      },
      {
        "path": "sprites/player/Player_Base_animations.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Player Base animations"
      },
      {
        "path": "sprites/player/Shoes_1_Brown.png",
        "tileW": 64,
        "tileH": 64,
        "label": "Shoes 1 Brown"
      }
    ]
  },
  {
    "name": "Other",
    "sheets": [
      {
        "path": "sprites/other/Bow_Stages.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Bow Stages"
      },
      {
        "path": "sprites/other/Ladder.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Ladder"
      },
      {
        "path": "sprites/other/Lantern_Torch.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Lantern Torch"
      },
      {
        "path": "sprites/other/Skeleton_Mage_Projectile.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Skeleton Mage Projectile"
      }
    ]
  },
  {
    "name": "Weather",
    "sheets": [
      {
        "path": "sprites/weather/Clouds.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Clouds"
      },
      {
        "path": "sprites/weather/Rain_Drop.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Rain Drop"
      },
      {
        "path": "sprites/weather/Rain_Drop_Impact.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Rain Drop Impact"
      },
      {
        "path": "animations/weather/Wind_Anim.png",
        "tileW": 16,
        "tileH": 16,
        "label": "Wind Anim",
        "animated": true
      }
    ]
  }
];
